[package]
name = "bugdemo"
version = "0.1.0"
authors = ["Sibz <12050358+Sibz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.0-preview.0"